name: Python Package using Conda

on:
  push:
    paths:
    - 'camera/**'

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: '3.7'
    - name: Add conda to system path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH
    - name: Install conda dependencies
      working-directory: ./camera
      run: |
        conda env update --file dependencies/conda_base_environment.yml --name base
    - name: Create virtual environment
      working-directory: ./camera
      run: |
        conda create --name cz3002_venv --file dependencies/cz3002_venv_linux.txt
    - name: Activate virtual environment
      run: |
        # eval function is needed to make conda activate able to run
        eval "$(conda shell.bash hook)"
        conda activate cz3002_venv
    - name: Install pip dependencies
      working-directory: ./camera
      run: |
        pip install -r dependencies/requirements_linux.txt
    - name: Install opencv
      run: |
        # Required for cv2 module
        pip install opencv-python
    - name: Lint with flake8
      run: |
        conda install flake8
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Run tests.py
      working-directory: ./camera
      run: |
        ls
        python tests.py
    - name: Deactivate environment
      run: |
        eval "$(conda shell.bash hook)"
        conda deactivate
  
  build-windows:
    runs-on: windows-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: '3.7'
    - name: Install conda dependencies
      working-directory: ./camera
      run: |
        C:\Miniconda\condabin\conda.bat env update --file dependencies/conda_base_environment.yml --name base
        C:\Miniconda\condabin\conda.bat init powershell
    - name: Create virtual environment
      working-directory: ./camera
      run: |
        C:\Miniconda\condabin\conda.bat create --name cz3002_venv --file dependencies/cz3002_venv_windows.txt
    - name: Activate virtual environment
      run: |
        C:\Miniconda\condabin\conda.bat activate cz3002_venv
    - name: Install pip dependencies
      working-directory: ./camera
      run: |
        pip install --user -r dependencies/requirements_windows.txt
    - name: Lint with flake8
      run: |
        C:\Miniconda\condabin\conda.bat install flake8
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Install opencv
      run: |
        # Required for cv2 module
        pip install opencv-python
    - name: Run tests.py
      working-directory: ./camera
      run: |
        ls
        python tests.py
    - name: Deactivate environment
      run: |
        C:\Miniconda\condabin\conda.bat deactivate